import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 12,
    overflow: 'visible',
  },
  rotatable: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    color: '#e2e8f0',
    fontSize: 18,
    fontWeight: '700',
  },
  nameInput: {
    color: '#e2e8f0',
    backgroundColor: '#00000055',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 120,
    textAlign: 'center',
  },
  life: {
    color: '#f8fafc',
    fontSize: 64,
    fontWeight: '800',
  },
  controlsRow: {
    flexDirection: 'row',
    gap: 3,
    width: '100%',
    justifyContent: 'center',
  },
  controlsGrid: {
    width: '100%',
    gap: 3,
    alignItems: 'center',
  },
  btn: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  squareBtn: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  squareBtnCompact: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    color: '#0b1020',
    fontWeight: '800',
    fontSize: 16,
  },
  lifeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  poisonBadge: {
    color: '#22c55e',
    fontWeight: '900',
    fontSize: 18,
  },
  poisonToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00000055',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9999,
  },
  poisonToggleText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  lostWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  poisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 6,
  },
  poisonBtn: {
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  poisonCount: {
    color: '#e2e8f0',
    fontWeight: '900',
    minWidth: 56,
    textAlign: 'center',
  },
  poisonLabel: {
    color: '#e2e8f0',
    fontWeight: '800',
    paddingHorizontal: 6,
  },
  pressed: {
    opacity: 0.9,
  },
  rotateBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#00000055',
    padding: 8,
    borderRadius: 9999,
  },
  resetIconBtn: {
    position: 'absolute',
    top: 56,
    right: 8,
    backgroundColor: '#00000055',
    padding: 8,
    borderRadius: 9999,
  },
  paletteBtn: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#00000055',
    padding: 8,
    borderRadius: 9999,
  },
  cmdToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00000055',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9999,
  },
  leftTogglesRow: {
    position: 'absolute',
    top: 56,
    left: 8,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 3,
    zIndex: 2,
  },
  cmdToggleText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  timerToggle: {
    backgroundColor: '#00000055',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 9999,
  },
  timerBadge: {
    backgroundColor: '#111827',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: '#374151',
  },
  timerBadgeText: {
    color: '#e5e7eb',
    fontWeight: '800',
    fontSize: 12,
  },
  cmdOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000aa',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  cmdPanel: {
    width: '90%',
    maxWidth: 420,
    maxHeight: 100,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  timerPanel: {
    width: '90%',
    maxWidth: 340,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
  cmdTitle: {
    color: '#e2e8f0',
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  timerDisplay: {
    color: '#e2e8f0',
    fontWeight: '900',
    fontSize: 28,
    marginBottom: 8,
  },
  cmdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 6,
  },
  cmdDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#111',
  },
  cmdName: {
    flex: 1,
    color: '#e2e8f0',
    fontWeight: '800',
    marginLeft: 8,
  },
  cmdBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  cmdBtn: {
    backgroundColor: '#1e293b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  cmdBtnText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  cmdCount: {
    color: '#e2e8f0',
    fontWeight: '900',
    minWidth: 28,
    textAlign: 'center',
  },
  cmdClose: {
    marginTop: 10,
    paddingVertical: 10,
    backgroundColor: '#334155',
    borderRadius: 10,
    alignItems: 'center',
  },
  cmdCloseText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  namePanel: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
});

export default styles;
