import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 12,
    overflow: 'visible',
  },
  touchPads: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    flexDirection: 'row',
  },
  padLeft: {
    flex: 1,
  },
  padRight: {
    flex: 1,
  },
  padHighlight: {
    backgroundColor: '#ffffff22',
  },
  highlightOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 12,
    borderWidth: 8,
    // Simulate CSS 'outset' using per-side colors (top/left lighter, bottom/right darker)
    borderColor: '#7dd3fc',
    borderTopColor: '#bfe9ff',
    borderLeftColor: '#bfe9ff',
    borderRightColor: '#38bdf8',
    borderBottomColor: '#38bdf8',
    // Subtle glow to enhance raised effect
    shadowColor: '#7dd3fc',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  glowOverlay: {
    position: 'absolute',
    top: -2,
    right: -2,
    bottom: -2,
    left: -2,
    borderRadius: 14,
    borderWidth: 10,
    borderColor: '#7dd3fc',
    shadowColor: '#7dd3fc',
    shadowOpacity: 0.6,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  frameCornerTL: {
    position: 'absolute',
    top: 4,
    left: 4,
    width: 30,
    height: 30,
    borderTopLeftRadius: 10,
    borderTopWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#7dd3fc',
  },
  frameCornerTR: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 30,
    height: 30,
    borderTopRightRadius: 10,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderColor: '#7dd3fc',
  },
  frameCornerBR: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 30,
    height: 30,
    borderBottomRightRadius: 10,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderColor: '#7dd3fc',
  },
  frameCornerBL: {
    position: 'absolute',
    bottom: 4,
    left: 4,
    width: 30,
    height: 30,
    borderBottomLeftRadius: 10,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderColor: '#7dd3fc',
  },
  raysContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  triRayWrap: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  triRay: {
    // Triangle pointing up using borders
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderBottomWidth: 60,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#fde047',
    opacity: 0.85,
  },
  ring: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 3,
    borderColor: '#fde047',
  },
  particlesContainer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  particle: {
    position: 'absolute',
    backgroundColor: '#7dd3fc',
    borderRadius: 9999,
    shadowColor: '#7dd3fc',
    shadowOpacity: 0.7,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 3,
  },
  rotatable: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  name: {
    color: '#e2e8f0',
    fontSize: 18,
    fontWeight: '700',
  },
  nameInput: {
    color: '#e2e8f0',
    backgroundColor: '#00000055',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    minWidth: 120,
    textAlign: 'center',
  },
  life: {
    color: '#f8fafc',
    fontSize: 64,
    fontWeight: '800',
  },
  lifeDelta: {
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  lifeDeltaOverlay: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  lifeDeltaPos: {
    color: '#22c55e',
  },
  lifeDeltaNeg: {
    color: '#ef4444',
  },
  controlsRow: {
    flexDirection: 'row',
    gap: 3,
    width: '100%',
    justifyContent: 'center',
  },
  controlsGrid: {
    width: '100%',
    gap: 3,
    alignItems: 'center',
  },
  btn: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  squareBtn: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  squareBtnCompact: {
    backgroundColor: '#0ea5e9',
    borderRadius: 10,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    color: '#0b1020',
    fontWeight: '800',
    fontSize: 16,
  },
  lifeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  poisonBadge: {
    color: '#22c55e',
    fontWeight: '900',
    fontSize: 18,
  },
  poisonToggle: {
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  poisonToggleText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  lostWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  poisonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 6,
  },
  poisonBtn: {
    backgroundColor: '#22c55e',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  poisonCount: {
    color: '#e2e8f0',
    fontWeight: '900',
    minWidth: 56,
    textAlign: 'center',
  },
  poisonLabel: {
    color: '#e2e8f0',
    fontWeight: '800',
    paddingHorizontal: 6,
  },
  pressed: {
    opacity: 0.9,
  },
  rotateBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resetIconBtn: {
    position: 'absolute',
    top: 56,
    right: 8,
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  paletteBtn: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cmdToggle: {
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leftTogglesRow: {
    position: 'absolute',
    top: 56,
    left: 8,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
    zIndex: 2,
  },
  cmdToggleText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  timerToggle: {
    backgroundColor: '#00000055',
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerBadge: {
    backgroundColor: '#111827',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: '#374151',
  },
  timerBadgeText: {
    color: '#e5e7eb',
    fontWeight: '800',
    fontSize: 12,
  },
  cmdOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000aa',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  cmdPanel: {
    width: '90%',
    maxWidth: 420,
    maxHeight: 100,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  timerPanel: {
    width: '90%',
    maxWidth: 340,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
  cmdTitle: {
    color: '#e2e8f0',
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  timerDisplay: {
    color: '#e2e8f0',
    fontWeight: '900',
    fontSize: 28,
    marginBottom: 8,
  },
  cmdRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 6,
  },
  cmdDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#111',
  },
  cmdName: {
    flex: 1,
    color: '#e2e8f0',
    fontWeight: '800',
    marginLeft: 8,
  },
  cmdBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  cmdBtn: {
    backgroundColor: '#1e293b',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  cmdBtnText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  cmdCount: {
    color: '#e2e8f0',
    fontWeight: '900',
    minWidth: 28,
    textAlign: 'center',
  },
  cmdClose: {
    marginTop: 10,
    paddingVertical: 10,
    backgroundColor: '#334155',
    borderRadius: 10,
    alignItems: 'center',
  },
  cmdCloseText: {
    color: '#e2e8f0',
    fontWeight: '800',
  },
  namePanel: {
    width: '90%',
    maxWidth: 360,
    backgroundColor: '#0b1020',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#334155',
    alignItems: 'center',
  },
});

export default styles;
